spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/demo_auth_store}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate.ddl-auto: validate

  liquibase:
    changeLog: classpath:/liquibase/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: false

security:
  app:
    jwtSecret: my_secret_jwt
    jwtExpirationMs: 86400000

